# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.6

from ......  import winsdk

_ns_module = winsdk._import_ns_module("Windows.ApplicationModel.DataTransfer.ShareTarget")

try:
    from ...  import contacts
except ImportError:
    pass

try:
    from ...  import datatransfer
except ImportError:
    pass

try:
    from .... foundation import collections
except ImportError:
    pass

try:
    from .... storage import streams
except ImportError:
    pass


QuickLink = _ns_module.QuickLink
ShareOperation = _ns_module.ShareOperation
